name: CI Angular + Spring Boot

on:
  push:
    branches: [ main ]
  

jobs:
  build-and-test:
    runs-on: maven

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: clean install and test
      run: mvn clean install

