name: CI Angular + Spring Boot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build Angular app
      working-directory: front
      run: |
        npm ci
        npm run build

    - name: Build Spring Boot app
      working-directory: back
      run: |
        ./mvnw clean package -DskipTests

    - name: Docker Compose up
      run: docker-compose up -d --build

    - name: Wait for services
      run: sleep 10

    # Exemple de test Angular
    - name: Run Angular tests
      working-directory: front
      run: npm test -- --watch=false --browsers=ChromeHeadless

   
    - name: Docker Compose down
      if: always()
      run: docker-compose down
