name: CI Angular + Spring Boot

on:
  push:
    branches: [ main ]
  

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest     

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: clean install and test
      working-directory: back
      run: mvn clean install

    - name: Generate JaCoCo Report
      working-directory: back
      run: mvn verify

  
 

  build-and-test-frontend:
    runs-on: ubuntu-latest     

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: clean install 
      working-directory: front
      run: npm install

    - name: test
      working-directory: front
      run: npm test -- --watch=false --browsers=ChromeHeadless
 
   
