name: CI Angular + Spring Boot

on:
  push:
    branches: [ main ]
  

jobs:
  build-and-test-backend:
    runs-on: maven

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: clean install and test
      run: mvn clean install

  build-and-test-frontend:
    runs-on: node

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: clean install 
      run: npm install

    - name: test
      run: npm test