name: Launch tests on PR
run-name: Launch tests on PR
on: [pull_request]
jobs:
  Test_Front:
    name: Build and Test Front
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build and Test
        run: |
          npm install
          npx ng test --watch=false --code-coverage

      - name: Upload Report
        uses: "actions/upload-artifact@v4"
        with:
          name: karma-report
          path: ${{ github.workspace }}/front/coverage
